---
language: node_js
node_js:
  - "0.12"
  - "iojs"

cache:
  directories:
    - node_modules

before_install:
  - export PATH=/usr/local/phantomjs-2.0.0/bin:$PATH
  - "npm config set spin false"
  - "npm install -g npm@^2"

install:
  - npm install
  - ./node_modules/ember-cli/node_modules/.bin/bower install

script:
  - npm test
